include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
  exclude:
    - docs/**

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
