name: fx_boot_starter
description: "a app start package to help handle start easy."
version: 0.1.1
homepage: https://github.com/TolyFx/fx
repository: https://github.com/TolyFx/fx/tree/main/modules/fx_boot_starter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

