name: fx_env
description: "flutter app environment checker"
version: 0.0.1+4
homepage: https://github.com/TolyFx/fx

environment:
  sdk: ^3.4.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
