name: fx_ability
description: "FrameworkX 宿主能力契约与全局注册入口，不包含平台实现。"
version: 0.1.1
homepage: https://github.com/TolyFx/fx
repository: https://github.com/TolyFx/fx/tree/main/interface/fx_ability

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
