name: fx_ability
description: "fx 能力抽象层，只定义接口契约，拒绝任何实现。"
version: 0.0.1
homepage: https://github.com/TolyFx/fx
repository: https://github.com/TolyFx/fx/tree/main/interface/fx_ability

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
